import type { Metadata } from 'next';
import HomePage from './home/page';
export const metadata: Metadata = {
  title: "Website Home",
  description: 'Generated by create next app',
};

export default HomePage;